import type { Workspace, Client, SavedQuote, Mail } from '../types/operations';
import { calculateCost, newDraft, FORMULA_VERSION } from './costing';
export const sampleCustomer: Client = { id: 'demo-northstar', name: 'Northstar Facilities', contact: 'Sarah Mitchell', email: 'sarah@northstar.example', phone: '+1 (416) 555-0142', billingAddress: '120 Example Avenue, Suite 200\nToronto, ON M5V 2T6', site: 'Toronto warehouse · 120 Example Avenue, Toronto, ON', bookId: 'standard', equipment: 'APC Smart-UPS · sample asset', notes: 'Illustrative customer for reviewing this dashboard. Contact details, equipment and history are examples.' };
export function withPreviewExample(data: Workspace): Workspace {
  const customers = data.customers.some(c => c.id === sampleCustomer.id) ? data.customers : [sampleCustomer, ...data.customers];
  const book = data.books.find(b => b.id === 'standard') || data.books[0];
  const draft = { ...newDraft(book, sampleCustomer.id, sampleCustomer.site), title: 'On-site UPS service assessment', customerSnapshot: sampleCustomer, notes: 'Example quotation only. Includes five hours of service. Parts and additional work require a separate quotation.', lines: book.items.map((r, i) => ({ ...r, id: `demo-line-${i}`, rateItemId: r.id, quantity: i === 0 ? 5 : 0 })) };
  const calc = calculateCost(draft);
  const quote: SavedQuote = { ...draft, id: 'demo-quote-northstar', number: 'EXAMPLE-001', revision: 1, status: 'Draft', createdAt: '2026-09-19T09:00:00Z', totalCost: calc.totalCost, sellingPrice: calc.sellingPrice, profit: calc.profit, formulaVersion: FORMULA_VERSION };
  const threadId = 'demo-northstar-thread';
  const messages: Mail[] = [
    { id: 'demo-mail-1', threadId, clientId: sampleCustomer.id, from: 'Sarah Mitchell', email: sampleCustomer.email, subject: 'UPS service at the Toronto warehouse', body: 'Hi Raza,\n\nCould you arrange a service assessment for the UPS at our Toronto warehouse? We would also like to understand whether the batteries need replacement.\n\nPlease let me know which equipment details you need.\n\nThanks,\nSarah', draft: '', date: '2026-09-18T13:00:00Z', category: 'Service', status: 'Archived', urgent: false, isRead: true, attachments: [] },
    { id: 'demo-mail-2', threadId, clientId: sampleCustomer.id, from: 'Raza · DCX', email: sampleCustomer.email, subject: 'RE: UPS service at the Toronto warehouse', body: 'Hi Sarah,\n\nPlease confirm the site address, UPS model and serial number, and your preferred service window. A photo of the equipment label would also help us prepare the assessment.\n\nRegards,\nRaza', draft: '', direction: 'outgoing', sentAt: '2026-09-18T13:25:00Z', date: '2026-09-18T13:25:00Z', category: 'Service', status: 'Archived', urgent: false, isRead: true, attachments: [] },
    { id: 'demo-mail-3', threadId, clientId: sampleCustomer.id, from: 'Sarah Mitchell', email: sampleCustomer.email, subject: 'RE: UPS service at the Toronto warehouse', body: 'Hi Raza,\n\nThe address is 120 Example Avenue, Toronto. It is an APC Smart-UPS. I have attached the equipment-label photo. We can arrange access next Tuesday morning.\n\nCan you send over a quotation for the assessment?\n\nThanks,\nSarah', draft: 'Hi Sarah,\n\nThank you for the site information. I am preparing a quotation for the service assessment and will confirm availability before scheduling the visit.\n\nRegards,\nRaza', date: '2026-09-19T08:30:00Z', category: 'Quotation', status: 'Needs review', urgent: false, attachments: ['equipment-label-example.jpg'], aiSummary: { text: 'Sarah requested a UPS assessment. DCX asked for the site and equipment details. Sarah provided a Toronto address, identified an APC Smart-UPS, and requested a quotation. Tuesday morning is her preference; no appointment has been confirmed.', generatedAt: '2026-09-19T08:31:00Z', sourceIds: ['demo-mail-1','demo-mail-2','demo-mail-3'] } },
  ];
  return { ...data, customers, quotes: data.quotes.some(q => q.id === quote.id) ? data.quotes : [quote, ...data.quotes], emails: data.emails.some(m => m.id === 'demo-mail-3') ? data.emails : [...messages, ...data.emails] };
}
