import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { normalizeMessage } from '../server/email-tracking-model.js';
import { trackingHandler } from '../server/email-tracking-api.js';
import { trackingDb } from './helpers/tracking-db.mjs';
import { createSession, configuration } from '../server/auth-core.js';

test('move-to-AI API stores an untracked conversation and hydrates the reply identity without a worker token',async t=>{
  const pg=await setup(t), db=trackingDb(pg);
  const env={APP_LOGIN_EMAIL:'owner@example.com',APP_LOGIN_PASSWORD:'long-test-password',APP_SESSION_SECRET:'s'.repeat(40),MAIL_PROVIDER:'microsoft',MICROSOFT_MAILBOX:'owner@example.com'};
  const message={id:'new-message',conversationId:'new-conversation',internetMessageId:'<new-message@example.com>',subject:'UPS service',from:{emailAddress:{address:'des@example.com'}},toRecipients:[{emailAddress:{address:'owner@example.com'}}],receivedDateTime:'2026-10-04T10:00:00Z',body:{contentType:'text',content:'Please quote next month.'},isDraft:false};
  const req={method:'POST',url:'/?action=prepare_ai',body:{message_id:message.id},headers:{host:'localhost:3000',origin:'http://localhost:3000',cookie:`dcx_session=${createSession(configuration(env))}`}};
  let output;const res={setHeader(){},end(v){output=JSON.parse(v);},statusCode:200};
  const provider=async action=>action==='message'?{record:message}:action==='thread'?{records:[message],next:null}:action==='attachments'?{records:[],next:null}:{mailbox:'owner@example.com'};
  await trackingHandler(req,res,env,{db,provider});
  assert.equal(res.statusCode,200,JSON.stringify(output));assert.equal(output.needs_generation,true);assert.deepEqual(output.draft.to_addresses,['des@example.com']);
  const stored=(await pg.query('select * from email_messages')).rows;assert.equal(stored.length,1);assert.equal(stored[0].body_loaded,true);assert.equal(stored[0].internet_message_id,message.internetMessageId);
  await trackingHandler(req,res,env,{db,provider});assert.equal(res.statusCode,200);assert.equal((await pg.query('select count(*)::int n from email_drafts')).rows[0].n,1);
});

test('custom report days respect Toronto boundaries and moving to AI drafts creates, reuses and restores one reply',async t=>{
  const pg=await setup(t);
  const box=(await pg.query("insert into email_mailboxes(provider,address) values('microsoft','owner@example.com') returning id")).rows[0].id;
  const ingest=async(id,when,sender='des@example.com')=>(await pg.query("select email_command($1,'ingest',$2::jsonb,'test') result",[box,JSON.stringify(normalizeMessage({id,conversationId:'custom-day',subject:'Re: UPS service',from:{emailAddress:{address:sender}},toRecipients:[{emailAddress:{address:'owner@example.com'}}],receivedDateTime:when,sentDateTime:when,body:{contentType:'text',content:'Please quote.'}},'microsoft','owner@example.com'))])).rows[0].result;
  const m=await ingest('start','2026-10-03T04:00:00Z');
  await ingest('last','2026-10-04T03:59:59Z');
  await ingest('next','2026-10-04T04:00:00Z','owner@example.com');
  const report=(await pg.query("select email_report_range($1,'2026-10-03','2026-10-03','America/Toronto') result",[box])).rows[0].result;
  assert.equal(report.received,2);assert.equal(report.sent,0);assert.equal(report.daily.length,1);assert.equal(report.conversations_replied,0);
  await assert.rejects(pg.query("select email_report_range($1,'2026-10-04','2026-10-03','UTC')",[box]),/valid date range/);
  const prep=async()=>(await pg.query("select crm_prepare_ai_draft($1,'test') result",[m.thread_id])).rows[0].result;
  const d=await prep();assert.equal(d.original_ai_body,null);assert.equal(d.current_body,'');assert.deepEqual(d.to_addresses,['des@example.com']);assert.equal((await prep()).id,d.id);
  await pg.query("update email_drafts set current_body='Reviewed reply',original_ai_body='AI reply' where id=$1",[d.id]);
  await pg.query("select crm_draft_trash(id,updated_at,false,'test') from email_drafts where id=$1",[d.id]);
  const restored=await prep();assert.equal(restored.id,d.id);assert.equal(restored.deleted_at,null);assert.equal(restored.current_body,'Reviewed reply');
  await pg.query("update email_drafts set status='sending' where id=$1",[d.id]);await assert.rejects(prep(),/Dispatch pending/);
  assert.equal((await pg.query('select count(*)::int n from email_messages')).rows[0].n,3);
});

async function setup(t){
  const pg=new PGlite();t.after(()=>pg.close());
  await pg.exec('create role anon;create role authenticated;create role service_role;');
  for(const name of ['202609160001_customer_crm.sql','202609230001_manageable_workspace.sql','202609230002_email_tracking.sql','202609240001_reporting_and_proposals.sql','202609270001_customer_quotations.sql','202610040001_email_memory.sql','202610040002_workspace_controls.sql','202610040003_email_relationships_learning.sql','202610040004_mail_navigation_reporting.sql'])await pg.exec(await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
  return pg;
}
test('workspace migrations preserve customer history and quotation snapshots through trash, restore and purge',async t=>{
  const pg=await setup(t);
  const c=(await pg.query("insert into crm_customers(name,email) values('ABC','des@example.com') returning *")).rows[0];
  await pg.query("insert into crm_contacts(customer_id,name,email) values($1,'Des','des@example.com')",[c.id]);
  const save=async(rate=13)=>(await pg.query("select crm_save_quotation($1,null,null,'Toronto',$2,false,$3) id",[c.id,JSON.stringify([{product_service:'Battery',description:'',quantity:2,unit_price:'100'}]),rate])).rows[0].id;
  const id=await save(5);
  let q=(await pg.query('select * from crm_quotations where id=$1',[id])).rows[0];
  assert.equal(Number(q.tax_total),10);assert.equal(Number(q.grand_total),210);
  await assert.rejects(save(100.001),/Tax rate/);
  await pg.query("insert into calculator_rate_versions(book_id,version,snapshot,saved_by) values('standard',1,'{}','owner'),('bgis',1,'{}','owner')");
  await assert.rejects(pg.query("select crm_retire_price_book('standard',1)"),/assigned to a customer/);
  await pg.query("update crm_customers set price_book='bgis' where id=$1",[c.id]);
  await pg.query("select crm_retire_price_book('standard',1)");
  assert.ok((await pg.query("select retired_at from calculator_rate_versions where book_id='standard'")).rows[0].retired_at);
  assert.equal((await pg.query('select count(*) n from calculator_rate_versions')).rows[0].n,2);
  await pg.query('select crm_delete_quotation($1,$2,1)',[c.id,id]);
  q=(await pg.query('select * from crm_quotations where id=$1',[id])).rows[0];assert.ok(q.deleted_at);
  await pg.query("select crm_quotation_trash($1,$2,$3,'restore')",[c.id,id,q.version]);
  q=(await pg.query('select * from crm_quotations where id=$1',[id])).rows[0];assert.equal(q.deleted_at,null);
  await assert.rejects(pg.query("select crm_quotation_trash($1,$2,$3,'purge')",[c.id,id,q.version]),/not in trash/);
  const current=(await pg.query('select updated_at from crm_customers where id=$1',[c.id])).rows[0];
  assert.equal((await pg.query('select crm_customer_trash($1,$2,false) result',[c.id,current.updated_at])).rows[0].result,true);
  assert.equal((await pg.query('select count(*) n from crm_contacts where customer_id=$1',[c.id])).rows[0].n,1);
  assert.equal((await pg.query("select crm_correspondent_role('des@example.com') r")).rows[0].r,'other');
  await assert.rejects(save(),/Customer not found/);
  const deleted=(await pg.query('select * from crm_customers where id=$1',[c.id])).rows[0];
  await pg.query('select crm_customer_trash($1,$2,true)',[c.id,deleted.updated_at]);
  await pg.query('select crm_delete_quotation($1,$2,$3)',[c.id,id,q.version]);
  q=(await pg.query('select * from crm_quotations where id=$1',[id])).rows[0];
  await pg.query("select crm_quotation_trash($1,$2,$3,'purge')",[c.id,id,q.version]);
  assert.equal((await pg.query('select count(*) n from crm_quotation_items where quotation_id=$1',[id])).rows[0].n,0);
});
test('exact domain classification, supplier routing, idempotent dispatch, draft restore and private learning',async t=>{
  const pg=await setup(t);
  assert.equal((await pg.query("select crm_correspondent_role('DES@dcx-tech.com') r")).rows[0].r,'staff');
  assert.equal((await pg.query("select crm_correspondent_role('des@dcx-tech.com.evil.example') r")).rows[0].r,'other');
  await pg.exec("insert into email_correspondent_roles(email,role,company) values('des@example.com','qualified_company','ABC');insert into product_supplier_routes(sku,product_name,supplier_email,auto_request) values('BAT-01','UPS Battery','supplier@example.com',true)");
  const box=(await pg.query("insert into email_mailboxes(provider,address) values('microsoft','owner@example.com') returning id")).rows[0].id;
  const thread=(await pg.query("insert into email_threads(mailbox_id,provider_thread_key,subject) values($1,'conv','Pricing') returning id",[box])).rows[0].id;
  const message=(await pg.query("insert into email_messages(thread_id,mailbox_id,provider_key,provider_ref,sender,subject,direction,body_text,occurred_at) values($1,$2,'in','in','des@example.com','Price request','incoming','Please send pricing. SKU: BAT-01 Qty: 4',now()) returning id",[thread,box])).rows[0].id;
  const request=(await pg.query('select * from supplier_price_requests')).rows[0];assert.equal(request.status,'queued');assert.equal(Number(request.quantity),4);
  await pg.query('select crm_supplier_request($1,$2,4)',[message,'BAT-01']);assert.equal((await pg.query('select count(*) n from supplier_price_requests')).rows[0].n,1);
  assert.equal((await pg.query('select crm_claim_supplier_request() r')).rows[0].r.claimed,true);
  assert.equal((await pg.query('select crm_claim_supplier_request() r')).rows[0].r.claimed,false);
  await pg.query("insert into email_messages(thread_id,mailbox_id,provider_key,provider_ref,sender,subject,direction,body_text,occurred_at) values($1,$2,'spoof','spoof','other@example.com',$3,'incoming','price',now())",[thread,box,request.request_subject]);
  assert.equal((await pg.query('select status from supplier_price_requests')).rows[0].status,'dispatching');
  await pg.query("insert into email_messages(thread_id,mailbox_id,provider_key,provider_ref,sender,subject,direction,body_text,occurred_at) values($1,$2,'answer','answer','supplier@example.com',$3,'incoming','price',now())",[thread,box,request.request_subject]);
  assert.equal((await pg.query('select status from supplier_price_requests')).rows[0].status,'answered');
  const d=(await pg.query("insert into email_drafts(thread_id,reply_to_message_id,current_body,original_ai_body,to_addresses,subject,source_message_version) values($1,$2,'Reviewed reply','Original AI reply','[\"des@example.com\"]','Reply',1) returning *",[thread,message])).rows[0];
  await pg.query('select crm_draft_trash($1,$2,false)',[d.id,d.updated_at]);
  await assert.rejects(pg.query("update email_drafts set current_body='Stale overwrite' where id=$1",[d.id]),/trash/);
  const trashed=(await pg.query('select * from email_drafts where id=$1',[d.id])).rows[0];
  const replacement=(await pg.query("insert into email_drafts(thread_id,reply_to_message_id,current_body,to_addresses,subject,source_message_version) values($1,$2,'New reply','[\"des@example.com\"]','Reply',1) returning id",[thread,message])).rows[0];
  await assert.rejects(pg.query('select crm_draft_trash($1,$2,true)',[d.id,trashed.updated_at]),/Another active draft/);
  await pg.query('delete from email_drafts where id=$1',[replacement.id]);
  await pg.query('select crm_draft_trash($1,$2,true)',[d.id,trashed.updated_at]);
  await pg.query("update email_drafts set status='sent' where id=$1",[d.id]);
  assert.equal((await pg.query('select count(*) n from email_learning_examples')).rows[0].n,1);
  // Latest inbound is now the supplier. Customer examples must not leak to them.
  const context=(await pg.query('select crm_ai_context($1) r',[thread])).rows[0].r;
  assert.equal(context.identity,'supplier@example.com');assert.equal(context.reviewed_examples.length,0);
  const categories=(await pg.query('select crm_email_categories() r')).rows[0].r;assert.equal(categories.roles.supplier,1);
  const contextPrices=context.supplier_price_requests;assert.equal(contextPrices[0].supplier_reply,'price');
  const otherThread=(await pg.query("insert into email_threads(mailbox_id,provider_thread_key,subject) values($1,'unknown-product','Pricing') returning id",[box])).rows[0].id;
  await pg.query("insert into email_messages(thread_id,mailbox_id,provider_key,provider_ref,sender,subject,direction,body_text,occurred_at) values($1,$2,'unknown-product','unknown-product','des@example.com','Pricing','incoming','Price please. SKU: UNKNOWN Qty: 2',now())",[otherThread,box]);
  assert.equal((await pg.query("select status from supplier_price_requests where sku='UNKNOWN'")).rows[0].status,'needs_supplier');
  await pg.query("insert into email_messages(thread_id,mailbox_id,provider_key,provider_ref,sender,subject,direction,body_text,occurred_at) values($1,$2,'multi-product','multi-product','des@example.com','Pricing','incoming','Price please. SKU: BAT-01 Qty: 4 SKU: UNKNOWN Qty: 2',now())",[otherThread,box]);
  assert.equal((await pg.query("select status,quantity from supplier_price_requests r join email_messages m on m.id=r.message_id where m.provider_key='multi-product'")).rows[0].status,'needs_details');
});
