import {workflow,trigger,node,vectorStore,embedding,documentLoader,expr,splitInBatches,nextBatch} from '@n8n/workflow-sdk';

const schedule=trigger({type:'n8n-nodes-base.scheduleTrigger',version:1.4,config:{name:'Index new emails every five minutes',parameters:{rule:{interval:[{field:'minutes',minutesInterval:5}]}},output:[{json:{}}]}});
const queue=node({type:'n8n-nodes-base.postgres',version:2.7,config:{name:'Queue missing historical emails',parameters:{operation:'executeQuery',query:'SELECT public.crm_queue_email_backfill(200) AS queued_sources;',options:{}},credentials:{postgres:{id:'ddSGCZFM8FCex3f8',name:'Postgres account'}},output:[{json:{queued_sources:0}}]}});
const claim=node({type:'n8n-nodes-base.postgres',version:2.7,config:{name:'Claim queued email chunks',parameters:{operation:'executeQuery',query:'SELECT * FROM public.crm_claim_email_embeddings(16);',options:{}},credentials:{postgres:{id:'ddSGCZFM8FCex3f8',name:'Postgres account'}},output:[{json:{id:'00000000-0000-4000-8000-000000000001',source_version:'synthetic-version',content:'Synthetic email evidence',lease_token:'00000000-0000-4000-8000-000000000002'}}]}});
const each=splitInBatches({version:3,config:{name:'One email chunk at a time',parameters:{batchSize:1},output:[{json:{id:'00000000-0000-4000-8000-000000000001',source_version:'synthetic-version',content:'Synthetic email evidence'}}]}});
const model=embedding({type:'@n8n/n8n-nodes-langchain.embeddingsOpenAi',version:1.2,config:{name:'Private email embeddings',parameters:{model:'text-embedding-3-small',options:{dimensions:1536,timeout:120,batchSize:16}},output:[{json:{}}]}});
const documents=documentLoader({type:'@n8n/n8n-nodes-langchain.documentDefaultDataLoader',version:1.1,config:{name:'Load the claimed email text',parameters:{dataType:'json',jsonMode:'expressionData',jsonData:expr('{{ $json.content }}'),textSplittingMode:'simple',options:{metadata:{metadataValues:[{name:'queue_id',value:expr('{{ $json.id }}')},{name:'source_version',value:expr('{{ $json.source_version }}')},{name:'model',value:'text-embedding-3-small'}]}}},output:[{json:{}}]}});
const insert=node({type:'@n8n/n8n-nodes-langchain.vectorStoreSupabase',version:1.3,config:{name:'Store private email vectors',parameters:{mode:'insert',tableName:{__rl:true,mode:'id',value:'crm_email_vectors'},embeddingBatchSize:16,options:{queryName:'match_email_memory_chunks'}},credentials:{supabaseApi:{id:'UWlDdtOOI61vsKM8',name:'Supabase account'}},subnodes:{embedding:model,documentLoader:documents},output:[{json:{}}]}});
const finish=node({type:'n8n-nodes-base.postgres',version:2.7,config:{name:'Confirm indexed source versions',executeOnce:true,parameters:{operation:'executeQuery',query:'SELECT public.crm_finish_email_embeddings($1::jsonb) AS confirmed;',options:{queryReplacement:expr('{{ [JSON.stringify($("Claim queued email chunks").all().map(i => ({id:i.json.id,lease_token:i.json.lease_token,source_version:i.json.source_version})))] }}')}},credentials:{postgres:{id:'ddSGCZFM8FCex3f8',name:'Postgres account'}},output:[{json:{confirmed:1}}]}});
export default workflow('dcx-email-memory-indexer','DCX private email memory indexer').add(schedule).to(queue).to(claim).to(each.onEachBatch(insert.to(finish.to(nextBatch(each)))));

