import { useState } from 'react';
import { Plus, FileText, Printer } from 'lucide-react';
import type { Workspace, SavedQuote } from '../../types/operations';
import { money, calculateCost } from '../../lib/costing';
import { QuotePrint } from './QuotePrint';
export function CustomerQuotes({ data, onNew, onRevise, onApprove, focusId }: { data: Workspace; onNew: () => void; onRevise: (q: SavedQuote) => void; onApprove: (q: SavedQuote) => void; focusId?: string; embedded?: boolean }) {
  const [selected, setSelected] = useState(focusId || ''); const [print, setPrint] = useState<SavedQuote | null>(null);
  const quote = data.quotes.find(q => q.id === selected);
  return <><section className="panel customer-quotes"><div className="panel-heading"><div><h2>Customer quotations</h2><p className="small muted">Saved revisions · printable customer copies</p></div><button className="secondary" onClick={onNew}><Plus size={15} /> New quotation</button></div>{!data.quotes.length ? <div className="empty-state"><FileText size={30} /><h3>Prepare their first quotation</h3><p>The customer's details and pricing agreement will be filled in for you.</p><button className="primary" onClick={onNew}>Create quotation</button></div> : <div className="table-scroll"><table><thead><tr><th>Quotation / scope</th><th>Created</th><th>Total incl. tax</th><th>Status</th><th>Customer copy</th></tr></thead><tbody>{data.quotes.map(q => <tr key={q.id}><td><button className="text-button" onClick={() => setSelected(q.id)}>{q.number} · r{q.revision}</button><small className="table-sub">{q.title}</small></td><td>{new Date(q.createdAt).toLocaleDateString('en-CA')}</td><td>{money(calculateCost(q).cadTotal * (q.currency === 'USD' ? q.usdRate : 1), q.currency)} {q.currency}</td><td><span className={`pill ${q.status === 'Approved' ? 'green' : 'amber'}`}>{q.status}</span></td><td><button className="secondary compact" onClick={() => setPrint(q)}><Printer size={14} /> Print / PDF</button></td></tr>)}</tbody></table></div>}</section>{quote && <div className="modal-backdrop"><section className="detail-modal" role="dialog" aria-modal="true" aria-label="Quotation details"><div className="panel-heading"><div><p className="eyebrow">{quote.number} · r{quote.revision}</p><h2>{quote.title}</h2></div><button className="text-button" onClick={() => setSelected('')}>Close</button></div><p>{quote.customerSnapshot?.name || data.customers.find(c => c.id === quote.customerId)?.name}</p><p>{quote.site}</p><div className="summary-details"><p className="summary-row"><span>Internal cost</span><strong>{money(quote.totalCost)}</strong></p><p className="summary-row"><span>Selling price · CAD</span><strong>{money(quote.sellingPrice)}</strong></p><p className="summary-row"><span>Profit</span><strong>{money(quote.profit)}</strong></p></div><p className="small muted">{quote.status} · Rate version {quote.bookVersion}. Saved customer details and prices stay with this revision.</p><div className="button-row"><button className="secondary" onClick={() => { setSelected(''); onRevise(quote); }}>Create revision</button>{quote.status !== 'Approved' && <button className="primary" onClick={() => onApprove(quote)}>Approve quotation</button>}<button className="secondary" onClick={() => setPrint(quote)}><Printer size={15} /> Print / PDF</button></div></section></div>}{print && <QuotePrint quote={print} customer={data.customers.find(c => c.id === print.customerId)} onClose={() => setPrint(null)} />}</>;
}
