import { useEffect, useState } from 'react';
import { crmRequest } from '../../lib/crm-client';

const roles=['staff','customer','qualified_company','lead','supplier','other'];
const topics=['pricing','quotation','order','service','technical','billing','meeting','other'];
const label=(value:string)=>value.replace(/_/g,' ');
const blankRoute=()=>({sku:'',product_name:'',supplier_email:'',auto_request:false});

export function EmailBrainPanel({navigate}:{navigate:(tab:string,id?:string)=>void}) {
  const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [role,setRole]=useState('all'),[topic,setTopic]=useState('all'),[route,setRoute]=useState<any>(blankRoute());
  const [request,setRequest]=useState({thread_id:'',sku:'',quantity:''});
  const [quantities,setQuantities]=useState<Record<string,string>>({});
  const [person,setPerson]=useState({email:'',role:'customer',company:''});
  async function load(){try{const result=await crmRequest('action=email-brain');if(!result.categories||!Array.isArray(result.categories.records))throw new Error('Email categories are unavailable. Apply the email brain migrations.');setData(result);setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void load();},[]);
  async function update(input:Record<string,unknown>){if(busy)return;setBusy(true);setError('');try{await crmRequest('action=email-brain',{method:'POST',body:JSON.stringify(input)});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const rows=(data?.categories.records||[]).filter((r:any)=>(role==='all'||r.role===role)&&(topic==='all'||r.topic===topic));
  return <section className="panel email-brain-panel"><div className="panel-heading"><div><h2>Email categories & relationships</h2><p className="small muted">Conversations tracked in the shared inbox. DCX domain senders appear as staff.</p></div><button className="secondary" onClick={()=>void load()} disabled={busy}>Refresh</button></div>
    {error&&<p role="alert" className="notice amber">{error}</p>}
    {data&&<><div className="button-row"><button className="secondary" onClick={()=>setRole('all')}>All conversations ({data.categories.total})</button>{roles.map(r=><button key={r} className={role===r?'primary':'secondary'} onClick={()=>setRole(r)}>{label(r)} ({data.categories.roles[r]||0})</button>)}</div>
    <div className="button-row"><button className="secondary" onClick={()=>setTopic('all')}>All topics</button>{topics.map(t=><button key={t} className={topic===t?'primary':'secondary'} onClick={()=>setTopic(t)}>{label(t)} ({data.categories.topics[t]||0})</button>)}</div>
    <p className="small muted">Counts cover all tracked conversations. Showing up to 200 recent conversations; classification is editable.</p>
    <div className="table-scroll"><table><thead><tr><th>Who we're talking to</th><th>Relationship</th><th>Email category</th><th>Status</th><th>Conversation</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.thread_id}><td>{r.email}{r.company&&<small>{r.company}</small>}</td><td><select aria-label={`Classify ${r.email}`} disabled={busy||r.role==='staff'} value={r.role} onChange={e=>void update({operation:'role',email:r.email,role:e.target.value,company:r.company})}>{roles.map(v=><option value={v} key={v}>{label(v)}</option>)}</select></td><td><select aria-label={`Category of ${r.subject}`} value={r.topic} disabled={busy} onChange={e=>void update({operation:'topic',thread_id:r.thread_id,topic:e.target.value})}>{topics.map(v=><option value={v} key={v}>{label(v)}</option>)}</select></td><td>{label(r.status)}</td><td><button className="text-button" onClick={()=>navigate('inbox',r.thread_id)}>{r.subject||'Open conversation'}</button><small>{new Date(r.last_activity_at||r.occurred_at).toLocaleDateString()}</small></td></tr>)}</tbody></table></div>
    <details><summary>Assign a company / relationship</summary><div className="form-grid"><label>Email<input type="email" value={person.email} onChange={e=>setPerson({...person,email:e.target.value})}/></label><label>Company<input maxLength={200} value={person.company} onChange={e=>setPerson({...person,company:e.target.value})}/></label><label>Relationship<select value={person.role} onChange={e=>setPerson({...person,role:e.target.value})}>{roles.filter(r=>r!=='staff').map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label></div><button className="secondary" disabled={busy} onClick={()=>void update({operation:'role',...person})}>Save classification</button></details>
    <details><summary>Supplier price automation</summary><p>Save the exact product SKU and its supplier. Enable automatic requests for products you want sent automatically. Emails with explicit “SKU: …” and “Qty: …” are routed; other pricing requests remain visible above for review.</p>
    <div className="form-grid"><label>Product SKU<input maxLength={100} value={route.sku} onChange={e=>setRoute({...route,sku:e.target.value})}/></label><label>Product name<input maxLength={200} value={route.product_name} onChange={e=>setRoute({...route,product_name:e.target.value})}/></label><label>Supplier email<input type="email" value={route.supplier_email} onChange={e=>setRoute({...route,supplier_email:e.target.value})}/></label><label><input type="checkbox" checked={route.auto_request} onChange={e=>setRoute({...route,auto_request:e.target.checked})}/> Automatically request supplier pricing</label></div>
    <div className="button-row"><button className="primary" disabled={busy} onClick={()=>void update({operation:'route',...route})}>Save supplier route</button><button className="secondary" onClick={()=>setRoute(blankRoute())}>New route</button></div>
    <div className="table-scroll"><table><thead><tr><th>SKU / product</th><th>Supplier</th><th>Automation</th><th>Actions</th></tr></thead><tbody>{data.routes.map((r:any)=><tr key={r.id}><td>{r.sku} — {r.product_name}</td><td>{r.supplier_email}</td><td>{r.auto_request?'Automatic':'Manual review'}</td><td><button className="text-button" onClick={()=>setRoute(r)}>Edit</button><button className="text-button" disabled={busy} onClick={()=>{if(window.confirm(`Delete supplier route for ${r.sku}?`))void update({operation:'delete-route',id:r.id,updated_at:r.updated_at});}}>Delete</button></td></tr>)}</tbody></table></div>
    <h3>Request a price for a conversation</h3><div className="form-grid"><label>Conversation<select value={request.thread_id} onChange={e=>setRequest({...request,thread_id:e.target.value})}><option value="">Choose customer email</option>{data.categories.records.filter((r:any)=>!['staff','supplier'].includes(r.role)).map((r:any)=><option key={r.thread_id} value={r.thread_id}>{r.email} — {r.subject}</option>)}</select></label><label>Exact SKU<input value={request.sku} onChange={e=>setRequest({...request,sku:e.target.value})}/></label><label>Quantity<input type="number" min="0.001" step="0.001" value={request.quantity} onChange={e=>setRequest({...request,quantity:e.target.value})}/></label></div><button className="secondary" disabled={busy} onClick={()=>void update({operation:'request',...request,quantity:request.quantity?Number(request.quantity):null})}>Prepare supplier request</button>
    <p className="small muted">Supplier dispatch runs through workflow 4 after deployment. Customer replies remain drafts for review.</p>
    {data.requests.map((r:any)=><article className="crm-record" key={r.id}><div><strong>{r.product_name||r.sku}</strong><p>{r.supplier_email||'Supplier needed'} · Qty {r.quantity||'needed'} · {label(r.status)}</p>{r.error&&<p className="form-error">{r.error}</p>}</div><button className="text-button" onClick={()=>navigate('inbox',r.thread_id)}>View customer</button>{['queued','needs_details','needs_supplier','awaiting_approval'].includes(r.status)&&<div><input aria-label={`Quantity for ${r.sku}`} type="number" min="0.001" step="0.001" value={quantities[r.id]??r.quantity??''} onChange={e=>setQuantities({...quantities,[r.id]:e.target.value})}/><button className="secondary" disabled={busy} onClick={()=>{const target=data.routes.find((s:any)=>s.sku===r.sku)?.supplier_email;if(!target){setError('Save a supplier route for this SKU first.');return;}if(window.confirm(`Queue a price request to ${target} for ${r.sku}?`))void update({operation:'resolve-request',id:r.id,quantity:Number(quantities[r.id]??r.quantity)||null,approve:true});}}>Review & queue</button><button disabled={busy} className="text-button" onClick={()=>void update({operation:'cancel-request',id:r.id})}>Cancel request</button></div>}</article>)}
    </details>
    <details><summary>Client learning ({data.learning.length} recent confirmed replies)</summary><p>Confirmed replies provide examples for that exact correspondent. You can exclude an example from future AI context.</p>{data.learning.map((r:any)=><article className="crm-record" key={r.draft_id}><div>{r.recipient_emails.join(', ')}<small>{new Date(r.confirmed_at).toLocaleDateString()}</small></div><button className="secondary" disabled={busy} onClick={()=>void update({operation:'learning',draft_id:r.draft_id,enabled:!r.enabled})}>{r.enabled?'Exclude from learning':'Include in learning'}</button></article>)}</details></>}
  </section>;
}
