import { useState } from 'react';
import { ArrowRight, Check, FileText, Inbox as InboxIcon, Paperclip, PenLine, Save, Search, ShieldCheck, UserRound } from 'lucide-react';
import type { Workspace, Mail } from '../../types/operations';

export { ThreadInbox as InboxPage } from './ThreadInbox';
function LegacyInboxPage({ data, onUpdate, onQuote, onCompose, focusId }: { data: Workspace; onUpdate: (mail: Mail) => void; onQuote: (clientId: string) => void; onCompose: (mail: Mail) => void; focusId?: string }) {
  const [selected, setSelected] = useState(focusId || data.emails[0]?.id || ''); const [filter, setFilter] = useState('All'); const [search, setSearch] = useState(''); const [compose, setCompose] = useState(false);
  const mails = data.emails.filter(m => (filter === 'All' || m.category === filter || m.status === filter) && `${m.subject} ${m.from} ${m.email} ${m.body}`.toLowerCase().includes(search.toLowerCase()));
  const active = mails.find(m => m.id === selected) || mails[0];
  return <><div className="page-heading"><div><p className="eyebrow">COMMUNICATIONS</p><h1>Inbox</h1><p>Every request, with the customer context beside it.</p></div><button className="primary" onClick={() => setCompose(true)}><PenLine size={15} /> Compose draft</button></div><div className="toolbar"><div className="segmented">{['All', 'Needs review', 'Quotation', 'Service', 'Tender'].map(f => <button key={f} className={filter === f ? 'active' : ''} onClick={() => setFilter(f)}>{f}</button>)}</div><div className="search-field"><Search size={15} /><input aria-label="Search emails" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search conversations" /></div></div>
      <div className="inbox-layout"><section className="panel mail-list no-pad"><div className="list-caption"><span>{mails.length} conversations</span><span>Example mailbox</span></div>{mails.map(m => <button className={`mail-item ${active?.id === m.id ? 'active' : ''}`} key={m.id} onClick={() => setSelected(m.id)}><div className="mail-item-top"><strong>{m.from}</strong><time>{new Date(m.date).toLocaleDateString('en-CA', { month: 'short', day: 'numeric' })}</time></div><h3>{m.subject}</h3><p>{m.body}</p><div className="mail-tags"><span className="pill neutral">{m.category}</span>{m.urgent && <span className="pill red">Urgent</span>}{m.status === 'Approved' && <span className="pill green">Approved</span>}{m.status === 'Needs review' && <span className="unread-dot" />}</div></button>)}{!mails.length && <div className="empty-state"><InboxIcon size={28} /><p>No conversations match.</p></div>}</section>{active ? <MailDetail key={active.id} mail={active} data={data} onUpdate={onUpdate} onQuote={onQuote} /> : <section className="panel empty-state"><p>Select a conversation to get started.</p></section>}</div>
      {compose && <ComposeModal data={data} onClose={() => setCompose(false)} onSave={m => { onCompose(m); setSelected(m.id); setFilter('All'); setSearch(''); setCompose(false); }} />}
  </>;
}
function MailDetail({ mail, data, onUpdate, onQuote }: { mail: Mail; data: Workspace; onUpdate: (m: Mail) => void; onQuote: (id: string) => void }) {
  const [draft, setDraft] = useState(mail.draft); const [tab, setTab] = useState('Conversation');
  const client = data.customers.find(c => c.id === mail.clientId); const dirty = draft !== mail.draft;
  const thread = data.emails.filter(m => m.threadId === mail.threadId).sort((a, b) => a.date.localeCompare(b.date));
  return <section className="panel no-pad mail-detail"><div className="mail-detail-header"><span className="pill neutral">{mail.category}</span><h2>{mail.subject}</h2><div className="mail-sender"><div className="avatar">{mail.from.slice(0, 1)}</div><div><strong>{mail.from}</strong><small>{mail.email}</small></div><span className="pill amber">{mail.status}</span></div></div><div className="detail-tabs">{['Conversation', 'Customer context'].map(t => <button className={tab === t ? 'active' : ''} onClick={() => setTab(t)} key={t}>{t}</button>)}</div>
    {tab === 'Conversation' ? <div className="mail-body">{thread.map(m => <div key={m.id}><p className="small muted">{m.direction === 'outgoing' ? 'Draft to' : 'From'} {m.email} · {new Date(m.date).toLocaleString()}</p><p className="pre-line">{m.body}</p></div>)}{mail.attachments.length > 0 && <div className="attachment-list">{mail.attachments.map(a => <div key={a}><Paperclip size={14} /><span>{a}</span><small>Metadata only</small></div>)}</div>}</div> : <div className="mail-body"><div className="context-card"><UserRound size={20} /><div><h3>{client?.name || 'Customer match needed'}</h3><p>{client?.site || 'Link this request to a customer record.'}</p></div></div><label>Linked customer<select value={mail.clientId} onChange={e => onUpdate({ ...mail, clientId: e.target.value, status: 'Needs review' })}><option value="">Unassigned</option>{data.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{client && <><dl className="context-facts"><dt>Price book</dt><dd>{data.books.find(b => b.id === client.bookId)?.name}</dd><dt>Equipment</dt><dd>{client.equipment}</dd><dt>Notes</dt><dd>{client.notes || 'No notes yet.'}</dd></dl><h3 className="small">Other conversations</h3>{data.emails.filter(m => m.clientId === client.id && m.id !== mail.id).map(m => <p className="related-mail small" key={m.id}><FileText size={13} />{m.subject}</p>)}</>}</div>}
    <div className="draft-section"><div className="panel-heading"><h3><PenLine size={15} /> Reply draft</h3><span className="small muted">Editable · human review</span></div><textarea aria-label="Reply draft" rows={8} value={draft} onChange={e => setDraft(e.target.value)} placeholder="Write your reply…" /><p className="field-help">Drafts stay in this workspace until Microsoft email is connected.</p><div className="button-row"><button className="secondary" disabled={!draft.trim() || !dirty} onClick={() => onUpdate({ ...mail, draft, status: 'Draft saved' })}><Save size={14} /> Save draft</button><button className="primary" disabled={!draft.trim()} onClick={() => onUpdate({ ...mail, draft, status: 'Approved' })}><Check size={15} /> Approve draft</button><button className="text-button" onClick={() => onUpdate({ ...mail, status: mail.status === 'Archived' ? 'Needs review' : 'Archived' })}>{mail.status === 'Archived' ? 'Restore' : 'Archive'}</button></div></div><div className="mail-detail-footer"><ShieldCheck size={15} /><span>Approval does not send an email.</span><button className="text-button" onClick={() => onQuote(mail.clientId)}>Build quotation <ArrowRight size={14} /></button></div>
  </section>;
}
export function ComposeModal({ data, onClose, onSave }: { data: Workspace; onClose: () => void; onSave: (m: Mail) => void }) {
  const [email, setEmail] = useState(''); const [subject, setSubject] = useState(''); const [body, setBody] = useState('');
  return <div className="modal-backdrop"><form className="detail-modal" role="dialog" aria-modal="true" aria-label="Compose email draft" onSubmit={e => { e.preventDefault(); const c = data.customers.find(c => c.email === email); onSave({ id: crypto.randomUUID(), threadId: crypto.randomUUID(), from: c?.name || email, email, clientId: c?.id || '', subject, body, draft: body, direction: 'outgoing', date: new Date().toISOString(), category: 'General', status: 'Draft saved', urgent: false, attachments: [] }); }}><div className="panel-heading"><h2>Compose a draft</h2><button type="button" className="text-button" onClick={onClose}>Close</button></div><label>To<input type="email" required value={email} onChange={e => setEmail(e.target.value)} list="customer-emails" /><datalist id="customer-emails">{data.customers.map(c => <option value={c.email} key={c.id}>{c.name}</option>)}</datalist></label><label>Subject<input required value={subject} onChange={e => setSubject(e.target.value)} /></label><label>Message<textarea required rows={8} value={body} onChange={e => setBody(e.target.value)} /></label><p className="small muted">This saves a local draft. No email will be sent.</p><button className="primary" disabled={!email.trim() || !subject.trim() || !body.trim()}><Save size={15} /> Save draft</button></form></div>;
}
