import { useEffect, useState } from 'react';
import { Check, ChevronRight, History, Info, Plus, Save, Trash2 } from 'lucide-react';
import type { Workspace, PriceBook, RateItem } from '../../types/operations';
import { bookUsable, money, today } from '../../lib/costing';
import { NumberField } from './CostWorkspace';

export function PriceBooks({ data, onSave, disabled = false, storageLabel }: { data: Workspace; onSave: (b: PriceBook) => Promise<PriceBook>; disabled?: boolean; storageLabel?: string }) {
  const [saving, setSaving] = useState(false);
  const [book, setBook] = useState<PriceBook>(() => structuredClone(data.books[0])); const [reviewed, setReviewed] = useState(false); const [error, setError] = useState(''); const [selected, setSelected] = useState(book.items[0]?.id || ''); const [dirty, setDirty] = useState(false);
  useEffect(() => {
    const beforeNavigate = (event: Event) => {
      if (saving || (dirty && !window.confirm('Discard unsaved rate changes?'))) event.preventDefault();
    };
    const beforeUnload = (event: BeforeUnloadEvent) => { if (dirty || saving) { event.preventDefault(); event.returnValue = ''; } };
    window.addEventListener('dcx-before-navigate', beforeNavigate);
    window.addEventListener('beforeunload', beforeUnload);
    return () => { window.removeEventListener('dcx-before-navigate', beforeNavigate); window.removeEventListener('beforeunload', beforeUnload); };
  }, [dirty, saving]);
  const patch = (p: Partial<PriceBook>) => { setBook(b => ({ ...b, ...p })); setReviewed(false); setDirty(true); };
  const item = book.items.find(r => r.id === selected);
  function itemPatch(p: Partial<RateItem>) { patch({ items: book.items.map(r => r.id === selected ? { ...r, ...p } : r) }); }
  function choose(id: string) { if (dirty && !window.confirm('Discard the unsaved edits to this price book?')) return; const b = structuredClone(data.books.find(x => x.id === id)!); setBook(b); setSelected(b.items[0]?.id || ''); setReviewed(false); setError(''); setDirty(false); }
  async function save(publish: boolean) {
    if (saving || disabled) return;
    if (!book.name.trim() || !book.effectiveFrom || (book.effectiveTo && book.effectiveTo < book.effectiveFrom)) return setError('Enter a name and valid effective dates.');
    if (!book.items.length || book.items.some(r => !r.description.trim() || ![r.supplierCost, r.multiplier, r.manualCost, r.margin, r.exchangeRate].every(Number.isFinite) || Math.min(r.supplierCost, r.multiplier, r.manualCost, r.margin) < 0 || r.margin >= 1 || r.exchangeRate <= 0)) return setError('Check the rates: costs cannot be negative, exchange must exceed zero, and margins must be below 100%.');
    if (publish && !reviewed) return setError('Confirm that the rates have been reviewed before publishing.');
    const original = data.books.find(b => b.id === book.id);
    const next: PriceBook = { ...book, version: original ? original.version + 1 : 1, status: publish ? 'Published' : 'Draft', updatedAt: new Date().toISOString() };
    setSaving(true);
    try { const saved = await onSave(next); setBook(saved); setReviewed(false); setError(''); setDirty(false); }
    catch (e) { setError((e as Error).message); }
    finally { setSaving(false); }
  }
  return <><p className="notice" role="status">{storageLabel}</p><fieldset disabled={saving || disabled} className="rates-fieldset"><div className="page-heading"><div><p className="eyebrow">PRICING CONTROL</p><h1>Calculator rates</h1><p>Change your rates. Keep your calculation rules consistent.</p></div><button className="secondary" onClick={() => { if (dirty && !window.confirm('Discard unsaved rate edits?')) return; const b: PriceBook = { ...structuredClone(data.books[0]), id: crypto.randomUUID(), name: 'New partner', description: 'Partner-specific rates. Review all starting values.', status: 'Draft', version: 1, effectiveFrom: today(), effectiveTo: '' }; setBook(b); setSelected(b.items[0]?.id || ''); setDirty(true); setReviewed(false); }}><Plus size={15} /> Add partner book</button></div>
    <div className="book-cards">{data.books.map(b => <button key={b.id} className={`book-card ${book.id === b.id ? 'active' : ''}`} onClick={() => choose(b.id)}><div><span className="book-initial">{b.name.slice(0, 1)}</span><span className={`pill ${bookUsable(b) ? 'green' : 'amber'}`}>{bookUsable(b) ? 'Active' : b.status === 'Draft' ? 'Draft' : 'Outside effective dates'}</span></div><h3>{b.name}</h3><p>{b.description}</p><footer><span>{b.items.length} rates · Version {b.version}</span><ChevronRight size={15} /></footer></button>)}</div>
    <section className="panel"><div className="panel-heading"><div><h2>{book.name} settings {dirty && <span className="pill amber">Unsaved edits</span>}</h2><p className="small muted">Workbook starting values are examples, not verified current Standard or BGIS prices.</p></div><span className="pill neutral">{book.status}</span></div><div className="form-grid four"><label>Price book name<input value={book.name} onChange={e => patch({ name: e.target.value })} /></label><label>Effective from<input type="date" value={book.effectiveFrom} onChange={e => patch({ effectiveFrom: e.target.value })} /></label><label>Effective until · optional<input type="date" value={book.effectiveTo} onChange={e => patch({ effectiveTo: e.target.value })} /></label><label>Agreement description<input value={book.description} onChange={e => patch({ description: e.target.value })} /></label></div></section>
    <div className="rate-layout"><section className="panel no-pad"><div className="panel-heading padded"><h2>Services & costs</h2><button className="text-button" onClick={() => { const r: RateItem = { id: crypto.randomUUID(), description: 'New service', supplier: '', unit: 'unit', costMode: 'manual', supplierCost: 0, manualCost: 0, multiplier: 1, exchangeRate: 1, margin: .3 }; patch({ items: [...book.items, r] }); setSelected(r.id); }}><Plus size={14} /> Add rate</button></div><div className="rate-list">{book.items.map(r => { const cost = r.costMode === 'manual' ? r.manualCost : r.supplierCost * r.multiplier; return <button className={`rate-item ${r.id === selected ? 'active' : ''}`} key={r.id} onClick={() => setSelected(r.id)}><div><strong>{r.description}</strong><small>{r.supplier || 'Custom'} · per {r.unit}</small></div><div className="rate-item-value"><strong>{money(cost)}</strong><small>{(r.margin * 100).toFixed(0)}% margin</small></div><ChevronRight size={14} /></button>; })}</div></section>
      <section className="panel rate-editor">{item ? <><div className="panel-heading"><h2>Edit rate</h2><button className="icon-button" aria-label="Remove selected rate" onClick={() => { patch({ items: book.items.filter(r => r.id !== item.id) }); setSelected(book.items.find(r => r.id !== item.id)?.id || ''); }}><Trash2 size={15} /></button></div><div className="form-grid"><label className="span-2">Description<input value={item.description} onChange={e => itemPatch({ description: e.target.value })} /></label><label>Supplier<input value={item.supplier} onChange={e => itemPatch({ supplier: e.target.value })} /></label><label>Unit<input value={item.unit} onChange={e => itemPatch({ unit: e.target.value })} /></label><label className="span-2">How is my cost determined?<select value={item.costMode} onChange={e => itemPatch({ costMode: e.target.value as 'manual' | 'multiplier' })}><option value="manual">Manual cost override</option><option value="multiplier">Supplier cost × multiplier</option></select></label><NumberField label="Supplier cost" value={item.supplierCost} onChange={supplierCost => itemPatch({ supplierCost })} /><NumberField label={item.costMode === 'manual' ? 'My cost override' : 'Cost multiplier'} value={item.costMode === 'manual' ? item.manualCost : item.multiplier} step="0.0001" onChange={v => itemPatch(item.costMode === 'manual' ? { manualCost: v } : { multiplier: v })} /><NumberField label="Target margin %" value={Number((item.margin * 100).toFixed(4))} max={99.99} onChange={v => itemPatch({ margin: v / 100 })} /><NumberField label="Exchange divisor" value={item.exchangeRate} step="0.0001" min={.0001} onChange={exchangeRate => itemPatch({ exchangeRate })} /></div><div className="rate-preview"><span>Indicative selling price / {item.unit}</span><strong>{item.margin < 1 && item.margin >= 0 && item.exchangeRate > 0 ? money((item.costMode === 'manual' ? item.manualCost : item.supplierCost * item.multiplier) / item.exchangeRate / (1 - item.margin)) : '—'}</strong></div>{item.sourceRow && <p className="field-help">Starting point: Job Cost Sheet, row {item.sourceRow}. Review before use.</p>}</> : <div className="empty-state"><p>Add a rate to begin.</p></div>}</section></div>
    <section className="panel publish-panel"><div><h2>Save a new version</h2><p className="small muted">Saved quotes keep their original amounts. A saved draft book pauses new approvals until published.</p><label className="checkbox-label"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /> I have reviewed these rates and their applicable agreement.</label>{error && <p role="alert" className="form-error">{error}</p>}</div><div className="button-row"><button className="secondary" onClick={() => save(false)}><Save size={15} /> Save draft</button><button className="primary" onClick={() => save(true)} disabled={!reviewed}><Check size={16} /> Publish version</button></div></section>
    <section className="panel"><div className="panel-heading"><h2><History size={16} /> Previous versions</h2></div>{data.bookHistory.filter(b => b.id === book.id).length ? data.bookHistory.filter(b => b.id === book.id).slice(0, 5).map(b => <div className="history-row" key={`${b.id}-${b.version}`}><span>Version {b.version} · {b.status}</span><span>{b.items.length} rates</span><time>{new Date(b.updatedAt).toLocaleString()}</time></div>) : <p className="small muted">Previous versions appear here after the next save.</p>}</section>
  </fieldset></>;
}
