import { useState } from 'react';
import { Inbox, Send, FileText, Archive, AlertCircle, Search, PenLine, Sparkles, Paperclip, Reply, Check, Save, UserRound } from 'lucide-react';
import type { Workspace, Mail } from '../../types/operations';
import { mailThreads } from '../../lib/mail-threads';
import { ComposeModal } from './Inbox';
type Props = { data: Workspace; onUpdate: (mail: Mail) => void; onQuote: (id: string) => void; onCompose: (mail: Mail) => void; focusId?: string };
const folders = [{ id: 'Inbox', icon: Inbox }, { id: 'Needs approval', icon: Check }, { id: 'Urgent', icon: AlertCircle }, { id: 'Drafts', icon: FileText }, { id: 'Sent', icon: Send }, { id: 'Archive', icon: Archive }];
export function ThreadInbox({ data, onUpdate, onQuote, onCompose, focusId }: Props) {
  const [folder, setFolder] = useState('Inbox'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(data.emails.find(m => m.id === focusId)?.threadId || ''); const [compose, setCompose] = useState(false);
  const threads = mailThreads(data.emails);
  const inFolder = (t: typeof threads[number], f: string) => f === 'Archive' ? t.archived : f === 'Sent' ? t.messages.some(m => !!m.sentAt) : f === 'Drafts' ? t.messages.some(m => !!m.draft.trim() && !m.sentAt) && !t.archived : f === 'Urgent' ? t.urgent && !t.archived : f === 'Needs approval' ? t.messages.some(m => m.status === 'Needs review') : !t.archived && t.messages.some(m => m.direction !== 'outgoing');
  const filtered = threads.filter(t => inFolder(t, folder) && t.messages.some(m => `${m.from} ${m.email} ${m.subject} ${m.body}`.toLowerCase().includes(query.toLowerCase())));
  const active = filtered.find(t => t.id === selected) || filtered[0];
  return <><div className="page-heading"><div><p className="eyebrow">CUSTOMER COMMUNICATIONS</p><h1>Mail</h1><p>Follow the conversation. See what happened and what comes next.</p></div><span className="pill neutral">Example mailbox · Microsoft not connected</span></div><div className="outlook-shell"><aside className="mail-folders"><button className="primary full" onClick={() => setCompose(true)}><PenLine size={15} /> New message</button><small>FOLDERS</small>{folders.map(f => <button key={f.id} className={folder === f.id ? 'active' : ''} onClick={() => { setFolder(f.id); setSelected(''); }}><f.icon size={16} /><span>{f.id}</span><b>{threads.filter(t => inFolder(t, f.id)).length}</b></button>)}<div className="mail-folder-foot"><span className="connection-dot" /> Local preview<p>Drafts and review actions stay here. Live sending is not enabled.</p></div></aside><section className="thread-list"><div className="thread-list-search"><Search size={15} /><input aria-label="Search mail conversations" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search mail" /></div><div className="list-caption"><strong>{folder}</strong><span>{filtered.length} conversations</span></div>{filtered.map(t => <button key={t.id} className={`thread-item ${active?.id === t.id ? 'active' : ''} ${t.unread ? 'unread' : ''}`} onClick={() => setSelected(t.id)}><div><strong>{t.messages.find(m => m.direction !== 'outgoing')?.from || t.latest.from}</strong><time>{new Date(t.latest.date).toLocaleDateString('en-CA', { month: 'short', day: 'numeric' })}</time></div><h3>{t.latest.subject.replace(/^RE:\s*/i, '')}</h3><p>{t.latest.body}</p><footer><span>{t.messages.length} message{t.messages.length === 1 ? '' : 's'}</span>{t.urgent ? <span className="pill red">Urgent</span> : <span className="pill neutral">{t.latest.category}</span>}{t.messages.some(m => m.attachments.length) && <Paperclip size={13} />}</footer></button>)}{!filtered.length && <div className="empty-state"><Inbox size={26} /><p>No matching conversations.</p></div>}</section>{active ? <ReadingPane key={active.id} thread={active} data={data} onUpdate={onUpdate} onQuote={onQuote} /> : <section className="reading-pane empty-state"><p>Select a conversation.</p></section>}</div>{compose && <ComposeModal data={data} onClose={() => setCompose(false)} onSave={m => { onCompose(m); setSelected(m.threadId); setFolder('Drafts'); setQuery(''); setCompose(false); }} />}</>;
}
function ReadingPane({ thread, data, onUpdate, onQuote }: { thread: ReturnType<typeof mailThreads>[number]; data: Workspace; onUpdate: (m: Mail) => void; onQuote: (id: string) => void }) {
  const mail = thread.latest; const [draft, setDraft] = useState(mail.draft); const [expanded, setExpanded] = useState<string[]>([mail.id]); const [context, setContext] = useState(false);
  const customer = data.customers.find(c => c.id === mail.clientId); const summary = [...thread.messages].reverse().find(m => m.aiSummary)?.aiSummary;
  const current = summary && thread.messages.every(m => summary.sourceIds.includes(m.id));
  const [dirty, setDirty] = useState(false);
  const save = () => { if (dirty) { onUpdate({ ...mail, draft, status: 'Draft saved' }); setDirty(false); } };
  return <section className="reading-pane"><header className="reading-heading"><span className="pill neutral">{mail.category}</span><h2>{mail.subject.replace(/^RE:\s*/i, '')}</h2><div className="mail-command-bar"><button className="text-button" onClick={() => setContext(!context)}><UserRound size={14} />{context ? 'Hide customer' : 'Customer details'}</button><button className="text-button" onClick={() => thread.messages.forEach(m => onUpdate({ ...m, isRead: !thread.unread }))}>{thread.unread ? 'Mark read' : 'Mark unread'}</button><button className="text-button" onClick={() => thread.messages.forEach(m => onUpdate({ ...m, status: thread.archived ? 'Needs review' : 'Archived' }))}><Archive size={14} />{thread.archived ? 'Restore' : 'Archive'}</button></div></header><div className="conversation-content"><section className="mail-intelligence"><div><Sparkles size={17} /><strong>{summary ? 'Example AI summary' : 'Conversation overview'}</strong><span className="pill neutral">{summary ? 'Demo content' : 'AI not connected'}</span></div><p>{summary ? summary.text : `${thread.messages.length} message${thread.messages.length === 1 ? '' : 's'} in this conversation. Latest request: ${mail.subject}.`}</p>{summary && <small>{current ? 'Based on all messages shown below.' : 'Summary needs refreshing for newer messages.'} Read the source messages before acting.</small>}<div className="conversation-next"><strong>Next action</strong><span>{mail.status === 'Approved' ? 'Draft approved locally. Awaiting Microsoft connection to send.' : thread.urgent ? 'Owner attention required. Review the request and confirm the response.' : mail.category === 'Quotation' ? 'Review the customer details and prepare a quotation.' : 'Review the latest message and reply draft.'}</span></div></section>
      {context && <section className="thread-customer"><h3>{customer?.name || 'Customer match needed'}</h3><p>{customer?.contact} · {customer?.phone || 'Phone not recorded'}</p><p>{customer?.billingAddress || customer?.site}</p><label>Linked customer<select value={mail.clientId} onChange={e => onUpdate({ ...mail, clientId: e.target.value, status: 'Needs review' })}><option value="">Unassigned</option>{data.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></section>}
      <div className="conversation-label"><span>{thread.messages.length} messages · oldest first</span><button className="text-button" onClick={() => setExpanded(expanded.length === thread.messages.length ? [mail.id] : thread.messages.map(m => m.id))}>{expanded.length === thread.messages.length ? 'Collapse history' : 'Expand all'}</button></div>{thread.messages.map(m => <article className={`conversation-message ${m.direction === 'outgoing' ? 'outgoing' : ''}`} key={m.id}><button className="conversation-message-header" onClick={() => setExpanded(expanded.includes(m.id) ? expanded.filter(id => id !== m.id) : [...expanded, m.id])} aria-expanded={expanded.includes(m.id)}><span className="avatar">{m.from[0]}</span><span><strong>{m.from}</strong><small>{m.direction === 'outgoing' ? `To: ${m.email}` : m.email}</small></span><span><time>{new Date(m.date).toLocaleString('en-CA', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</time><small>{m.direction === 'outgoing' ? m.sentAt ? 'Sent · sample history' : 'Unsent draft' : 'Received'}</small></span></button>{expanded.includes(m.id) ? <div className="conversation-message-body"><p className="pre-line">{m.body}</p>{m.attachments.length > 0 && <div className="attachment-list">{m.attachments.map(a => <div key={a}><Paperclip size={14} /><span>{a}</span><small>Example attachment</small></div>)}</div>}</div> : <p className="collapsed-message">{m.body}</p>}</article>)}
      <section className="conversation-reply"><div className="panel-heading"><h3><Reply size={16} /> Reply draft</h3><span className="pill neutral">{dirty ? 'Unsaved changes' : mail.status === 'Approved' ? 'Approved locally' : 'Not sent'}</span></div><textarea aria-label="Reply draft" rows={7} value={draft} onChange={e => { setDraft(e.target.value); setDirty(true); }} onBlur={save} placeholder="Write a response…" /><div className="button-row"><button className="secondary" onClick={() => { onUpdate({ ...mail, draft, status: 'Draft saved' }); setDirty(false); }} disabled={!draft.trim()}><Save size={14} /> Save draft</button><button className="primary" onClick={() => { onUpdate({ ...mail, draft, status: 'Approved' }); setDirty(false); }} disabled={!draft.trim()}><Check size={14} /> Approve draft</button><button className="text-button" onClick={() => onQuote(mail.clientId)}><FileText size={14} /> Customer quotation</button></div><p className="field-help">Preview only. Saving or approving does not send an email.</p></section></div></section>;
}
