import { useState } from 'react';
import { exportCostXlsx, exportCostJpg } from '../../lib/cost-export';
import { Plus, Trash2, Save, RefreshCw } from 'lucide-react';
import type { Workspace, QuoteDraft, CostLine } from '../../types/operations';
import { calculateCost, money, lineFromRate, bookUsable } from '../../lib/costing';
type Props = { data: Workspace; draft: QuoteDraft; onChange: (d: QuoteDraft) => void; onSave: (review: boolean) => void; onBack: () => void };
export function WorkbookCalculator({ data, draft, onChange, onSave }: Props) {
  const [exporting,setExporting]=useState(false), [exportError,setExportError]=useState('');
  async function exportTable(format:'xlsx'|'jpg'){setExporting(true);setExportError('');try{if(format==='xlsx')await exportCostXlsx(draft);else await exportCostJpg(draft);}catch(e){setExportError((e as Error).message);}finally{setExporting(false);}}
  const calc = calculateCost(draft); const book = data.books.find(b => b.id === draft.bookId) || data.books[0];
  const patch = (p: Partial<QuoteDraft>) => onChange({ ...draft, ...p });
  const linePatch = (id: string, p: Partial<CostLine>) => patch({ lines: draft.lines.map(l => l.id === id ? { ...l, ...p } : l) });
  const useBook = (id: string) => { const b = data.books.find(b => b.id === id)!; patch({ bookId: b.id, bookVersion: b.version, lines: b.items.map(r => lineFromRate(r, draft.lines.find(l => l.rateItemId === r.id)?.quantity || 0)) }); };
  const valid = calc.valid && !!draft.customerId && !!draft.title.trim() && !!draft.site.trim() && calc.sellingPrice > 0 && Number.isInteger(draft.validityDays) && draft.validityDays >= 1 && (draft.currency !== 'USD' || draft.usdRate > 0);
  const shown = (n: number) => Number.isFinite(n) ? money(n) : '—';
  return <div className="workbook"><div className="workbook-heading"><div><p className="eyebrow">INTERNAL ESTIMATE</p><h2>Job cost worksheet</h2></div><span className="pill neutral">Working draft · local</span></div><div className="workbook-details"><label>Company name<select aria-label="Quotation customer" value={draft.customerId} onChange={e => { const c = data.customers.find(c => c.id === e.target.value); if (!c) { patch({ customerId: '', customerSnapshot: undefined }); return; } const b = data.books.find(b => b.id === c.bookId) || data.books[0]; onChange({ ...draft, customerId: c.id, customerSnapshot: structuredClone(c), site: c.site, bookId: b.id, bookVersion: b.version, lines: b.items.map(r => lineFromRate(r, draft.lines.find(l => l.rateItemId === r.id)?.quantity || 0)) }); }}><option value="">Quick calculation · no customer</option>{data.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Pricing agreement<select value={book.id} onChange={e => useBook(e.target.value)}>{data.books.map(b => <option key={b.id} value={b.id}>{b.name} · v{b.version}</option>)}</select></label><label>Quote / revision<input readOnly value={draft.revises ? data.quotes.find(q => q.id === draft.revises)?.number || 'New revision' : 'Assigned when saved'} /></label><label>Scope<input value={draft.title} onChange={e => patch({ title: e.target.value })} /></label><label className="ship-to">Ship to / service address<input value={draft.site} placeholder="Customer site and address" onChange={e => patch({ site: e.target.value })} /></label></div>
    {(!bookUsable(book) || book.version !== draft.bookVersion) && <div className="worksheet-rate-note"><span>{book.name} · {book.version !== draft.bookVersion ? 'A newer rate version is available.' : 'Draft rates — review before approval.'}</span>{book.version !== draft.bookVersion && <button className="text-button" onClick={() => useBook(book.id)}><RefreshCw size={13} /> Refresh rates</button>}</div>}
    <div className="worksheet-scroll" tabIndex={0} aria-label="Job cost worksheet, scroll horizontally for all columns"><table className="worksheet-table"><thead><tr><th>Item #</th><th>Supplier</th><th>Description</th><th>Supplier<br />cost</th><th>Mult.</th><th>MY cost</th><th>Qty</th><th>Total<br />MY cost</th><th>Exch.<br />rate</th><th>Total CAD<br />with exchange</th><th>Margin</th><th>Mark up amt<br /><small>(profit)</small></th><th>Selling<br />price</th><th><span className="sr-only">Remove</span></th></tr></thead><tbody>{calc.lines.map((l, i) => <tr key={l.id}><td className="input-aqua">{i + 1}</td><td className="input-aqua"><input aria-label={`Item ${i + 1} supplier`} value={l.supplier} onChange={e => linePatch(l.id, { supplier: e.target.value })} /></td><td className="input-aqua"><input aria-label={`Item ${i + 1} description`} value={l.description} onChange={e => linePatch(l.id, { description: e.target.value })} /><input className="unit-input" aria-label={`Item ${i + 1} unit`} value={l.unit} onChange={e => linePatch(l.id, { unit: e.target.value })} /></td><td className="supplier-yellow"><Cell label={`${l.description} supplier cost`} value={l.supplierCost} change={v => linePatch(l.id, { supplierCost: v })} /></td><td className="mult-lavender"><Cell label={`${l.description} multiplier`} value={l.multiplier} change={v => linePatch(l.id, { multiplier: v })} /></td><td className="cost-pink"><Cell label={`${l.description} my cost`} value={l.unitCost} readOnly={l.costMode === 'multiplier'} change={v => linePatch(l.id, { manualCost: v })} /><select title="Entered cost uses your direct cost. Supplier × multiplier calculates it from the two columns to the left." aria-label={`${l.description} cost basis`} value={l.costMode} onChange={e => linePatch(l.id, { costMode: e.target.value as 'manual' | 'multiplier' })}><option value="manual">Entered cost</option><option value="multiplier">Supplier × mult.</option></select></td><td className="input-aqua"><Cell label={`${l.description} quantity`} value={l.quantity} change={v => linePatch(l.id, { quantity: v })} /></td><td>{shown(l.extendedCost)}</td><td className="input-aqua"><Cell label={`${l.description} exchange divisor`} value={l.exchangeRate} min={.0001} change={v => linePatch(l.id, { exchangeRate: v })} /></td><td>{shown(l.cadCost)}</td><td className="margin-blue"><Cell label={`${l.description} margin`} value={Number((l.margin * 100).toFixed(4))} max={99.99} change={v => linePatch(l.id, { margin: v / 100 })} /><small>%</small></td><td>{shown(l.profit)}</td><td className="worksheet-selling">{shown(l.sell)}</td><td><button className="icon-button" aria-label={`Remove ${l.description}`} onClick={() => patch({ lines: draft.lines.filter(x => x.id !== l.id) })}><Trash2 size={13} /></button></td></tr>)}</tbody></table></div>
    <div className="worksheet-actions"><button className="text-button" onClick={() => { const id = crypto.randomUUID(); patch({ lines: [...draft.lines, { id, rateItemId: id, supplier: '', description: 'Additional service', unit: 'unit', supplierCost: 0, multiplier: 1, manualCost: 0, costMode: 'manual', quantity: 1, exchangeRate: 1, margin: .3 }] }); }}><Plus size={14} /> Add item</button><span>Colored cells are inputs. White cells calculate automatically.</span></div>
    <section className="worksheet-flat"><div className="panel-heading"><h3>FLAT RATE ITEMS</h3><button className="text-button" onClick={() => patch({ flatLines: [...draft.flatLines, { id: crypto.randomUUID(), description: '', amount: 0, addition: 0 }] })}><Plus size={14} /> Add flat item</button></div><div className="worksheet-scroll"><table className="flat-sheet"><thead><tr><th>Item #</th><th>Description</th><th>Fixed amount</th><th>Addition</th><th>Selling price</th><th /></tr></thead><tbody>{draft.flatLines.map((f, i) => <tr key={f.id}><td>{i + 1}</td><td><input aria-label={`Flat item ${i + 1} description`} value={f.description} onChange={e => patch({ flatLines: draft.flatLines.map(x => x.id === f.id ? { ...x, description: e.target.value } : x) })} /></td><td><Cell label={`Flat item ${i + 1} amount`} value={f.amount} change={v => patch({ flatLines: draft.flatLines.map(x => x.id === f.id ? { ...x, amount: v } : x) })} /></td><td><Cell label={`Flat item ${i + 1} addition`} value={f.addition} change={v => patch({ flatLines: draft.flatLines.map(x => x.id === f.id ? { ...x, addition: v } : x) })} /></td><td>{shown(f.amount + f.addition)}</td><td><button className="icon-button" aria-label={`Remove flat item ${i + 1}`} onClick={() => patch({ flatLines: draft.flatLines.filter(x => x.id !== f.id) })}><Trash2 size={13} /></button></td></tr>)}</tbody></table></div>{!draft.flatLines.length && <p className="small muted">Add a fixed selling amount when needed.</p>}</section>
    <label className="worksheet-notes">NOTES / ASSUMPTIONS<textarea rows={2} value={draft.notes} onChange={e => patch({ notes: e.target.value })} /></label>
    <div className="worksheet-totals"><div><Total label="Total COST CAD$" value={shown(calc.totalCost)} /><Total label="Total selling price" value={shown(calc.sellingPrice)} /><Total label="Total profit" value={shown(calc.profit)} /></div><div><label>Shipping cost<Cell label="Shipping cost CAD" value={draft.shipping} change={v => patch({ shipping: v })} /></label><label>Brokerage fee<Cell label="Brokerage fee CAD" value={draft.brokerage} change={v => patch({ brokerage: v })} /></label><Total label="Gross profit margin" value={calc.valid && calc.grossMargin !== null ? `${(calc.grossMargin * 100).toFixed(2)}%` : '—'} /></div></div>
    <div className="worksheet-usd"><strong>QUOTING IN USD</strong><label>Exchange rate <Cell label="USD per CAD" value={draft.usdRate} change={v => patch({ usdRate: v })} /></label><span>CDN $ <strong>{shown(calc.sellingPrice)}</strong></span><span>USD $ <strong>{draft.usdRate > 0 && calc.valid ? money(calc.usdSellingPrice, 'USD') : 'Set exchange rate'}</strong></span></div>
    <div className="worksheet-legend"><p><i className="supplier-yellow" />Supplier cost: product, shipping or service cost.</p><p><i className="cost-pink" />My cost: manual override, or choose Calculated to use supplier × multiplier.</p><p><i className="mult-lavender" />Multiplier: used only for calculated cost rows.</p><p><i className="margin-blue" />Margin: selling price = CAD cost ÷ (1 − margin).</p></div>
    <div className="worksheet-final"><label>Quote currency<select value={draft.currency} onChange={e => patch({ currency: e.target.value as 'CAD' | 'USD' })}><option>CAD</option><option>USD</option></select></label><label>Tax %<Cell label="Quotation tax percent" value={draft.taxPercent} max={100} change={v => patch({ taxPercent: v })} /></label><label>Valid for (days)<Cell label="Quote validity days" value={draft.validityDays} min={1} step="1" change={v => patch({ validityDays: v })} /></label><div><small>Total including tax · {draft.currency}</small><strong>{calc.valid ? money(calc.cadTotal * (draft.currency === 'USD' ? draft.usdRate : 1), draft.currency) : '—'}</strong></div></div>
    <div className="toolbar"><div><strong>Export the complete cost table</strong><p className="field-help">All items, flat amounts, costs, profit, tax and notes. Internal use. Large JPG exports download numbered pages.</p></div><button className="secondary" disabled={exporting||!calc.valid} onClick={()=>exportTable('xlsx')}>{exporting?'Exporting?':'Download XLSX'}</button><button className="secondary" disabled={exporting||!calc.valid} onClick={()=>exportTable('jpg')}>Download JPG</button></div>{exportError&&<p className="form-error" role="alert">{exportError}</p>}
    {!calc.valid && <p role="alert" className="form-error">{calc.errors.slice(0, 3).join(' ')}</p>}<div className="worksheet-save"><p>{valid ? 'Save a fixed revision under this customer. Print it from their Quotations tab.' : 'For a quotation, select a customer, enter the address and scope, and add a positive amount.'}</p><button className="secondary" disabled={!valid} onClick={() => onSave(false)}>Save draft</button><button className="primary" disabled={!valid} onClick={() => onSave(true)}><Save size={15} /> Save quotation</button></div>
  </div>;
}
function Total({ label, value }: { label: string; value: string }) { return <p className="worksheet-total"><span>{label}</span><strong>{value}</strong></p>; }
function Cell({ label, value, change, min = 0, max, readOnly = false, step = 'any' }: { label: string; value: number; change: (n: number) => void; min?: number; max?: number; readOnly?: boolean; step?: string }) { return <input aria-label={label} type="number" step={step} min={min} max={max} readOnly={readOnly} value={Number.isFinite(value) ? Number(value.toFixed(6)) : ''} onChange={e => change(e.target.value === '' ? 0 : Number(e.target.value))} />; }
